export const Actions = {

  //FEATURE_LIST
  FEATURE_LIST: "FEATURE/FEATURE_LIST",
  FEATURE_LIST_REQUEST: "FEATURE/FEATURE_LIST_REQUEST",
  FEATURE_LIST_SUCCESS: "FEATURE/FEATURE_LIST_SUCCESS",
  FEATURE_LIST_FAILURE: "FEATURE/FEATURE_LIST_FAILURE",

  //FEATURE_DETAILS
  FEATURE_DETAILS: "FEATURE/FEATURE_DETAILS",
  FEATURE_DETAILS_REQUEST: "FEATURE/FEATURE_DETAILS_REQUEST",
  FEATURE_DETAILS_SUCCESS: "FEATURE/FEATURE_DETAILS_SUCCESS",
  FEATURE_DETAILS_FAILURE: "FEATURE/FEATURE_DETAILS_FAILURE",

};

export default Actions;
